<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Set;
use App\Models\Flashcard;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        $aidan = new User;
        $aidan->first_name = "Aidan";
        $aidan->last_name = "Crane";
        $aidan->username = "aidan";
        $aidan->friendly_name = "Aidan";
        $aidan->email_address = "aidancrane78@gmail.com";
        $aidan->email_verified_at = now();
        $aidan->password = Hash::make('password');
        $aidan->role = array('admin');
        $aidan->save();

        for ($k = 0 ; $k < 250; $k++) {
            $user = User::factory()->create();
            $user->username = $user->username . $k;
            Set::factory()->count(30)->create([
             'owner_id' => $user->id,
            ]);
            $user->save();
        }

        $set = new Set;
        $set->owner_id = $aidan->id;
        $set->set_title = "Dogs Quiz";
        $set->set_description = "A Quiz about dogs.";
        $set->category = "database-autogenerated-seeder";
        $set->creation_date = date('Y-m-d');
        $set->save();

        $flashcard = new Flashcard;
        $flashcard->front_text = "<center>\n\nExample Text!\n\n![German Shepherd](https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/22170353/German-Shepherd-Dog-running.jpg \"365x243\")\n\n</center>";
        $flashcard->back_text = "<center>German Shepherd</center>";
        $flashcard->flashcard_order = 1;
        $flashcard->set_id = $set->id;
        $flashcard->save();

        // \App\Models\User::factory(10)->create();
    }
}
